### ISSUE TITLE
Nenhum dado encontrado

### ISSUE THREAD

**Issue by cadorexbr** [guilhermecugler/Scraper-Casa-dos-Dados#1]
Falaa mestre! Tudo bem?
Testei mas nao esta puxando os dados quando coloco os filtros e nem puxa sem filtros, como posso proceder?

**Comment by guilhermecugler** [comment]
> Falaa mestre! Tudo bem? Testei mas nao esta puxando os dados quando coloco os filtros e nem puxa sem filtros, como posso proceder?

Opa, instalou todas dependências? Da algum erro no console? Acabei de rodar aqui e funcionou legal, apesar de não usar mais esse projeto pois estou desenvolvendo o mesmo com uma biblioteca gráfica melhor e utilizando threads.

**Comment by cadorexbr** [comment]
Consegues me chamar no wpp? 47 99240-3510
