### ISSUE TITLE
Request for English README.md version

### ISSUE THREAD

**Issue by timotheeMM** [guilhermecugler/Scraper-Casa-dos-Dados#4]
Hello @guilhermecugler,

I hope this message finds you well. I recently came across your repository and found it to be very good.

I noticed that the README.md is currently available only in Portuguese. As an English speaker (and French), I believe having an English version would greatly benefit a wider audience and increase accessibility.

I would like to contribute by providing an English translation for the README.md file. Could you please assign this issue to me so that I can start working on the translation?

Thank you for considering this request. I'm excited about the opportunity to contribute to your project.

Best regards,
timotheeMM

**Comment by guilhermecugler** [comment]
Hello @timotheeMM, I would be happy with your help, I have already assigned you to this issue!

**Comment by timotheeMM** [comment]
@guilhermecugler,
OK Thanks I'll start working on it soon.

**Comment by timotheeMM** [comment]
@guilhermecugler,
I have two questions:
First, for the title of the document, is README-en.md good?
Finally, do you want to keep as the main README the Portuguese version. Or the English version?

**Comment by guilhermecugler** [comment]
> @guilhermecugler, I have two questions: First, for the title of the document, is README-en.md good? Finally, do you want to keep as the main README the Portuguese version. Or the English version?

Yes, README-en.MD is good.
The main we can keep in Portuguese since the majority of users will be brazilians.
