### ISSUE TITLE
Problema ao Iniciar 

### ISSUE THREAD

**Issue by dsz20o7** [guilhermecugler/Scraper-Casa-dos-Dados#7]
Boa Tarde tudo bem sou novo aqui, achei bem interessante esse projeto tentei iniciar mais quando executo o casadosdados.py me aparece esse erro `requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
Se alguém puder me auxiliar desde já agradeço

**Comment by guilhermecugler** [comment]
O site casa dos dados está realizando alterações, assim que terminarem irei atualizar o projeto.
